#Aquí está el batch
gcc -O3 -Wall -c -o Text.o Text.c
ar -r libText.a Text.o

gcc -O3 -Wall -c -o Stack.o Stack.c
ar -r libStack.a Text.o

gcc -O3 -Wall -c -o Dictionary.o Dictionary.c
ar -r libDictionary.a Dictionary.o